inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 3.0.1
# 除外するディレクトリ（自動生成されたファイル）
  Exclude:
    - "bin/*"
    - "config/puma.rb"
    - "db/schema.rb"
    - "db/migrate/*"
    # 要最終確認
    - 'app/models/scraping.rb'

# ブロック内の行数をチェックする
Metrics/BlockLength:
  Exclude:
    - "spec/**/*"


# 文字列に値が代入されて変わっていないかチェック（無効）
Style/FrozenStringLiteralComment:
  Enabled: false

# クラスやモジュール定義前に、それらの説明書きがあるかをチェック（無効）
Style/Documentation:
  Enabled: false

# クラス内にクラスが定義されていないかチェック（無効）
Style/ClassAndModuleChildren:
  Enabled: false